### ISSUE TITLE
Node and edge features

### ISSUE THREAD

**Issue by tathagatv** [simonlinyj/Graph-Matching-Networks#3]
I'm trying to use this model with some node and edge features. Lines 229-230 in [dataset.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/dataset.py) of the _pack_batch function set node and edge feature dimensions as 1.
If I increase this size to any number >1, I'm getting runtime errors. The following was obtained on changing the node and feature dimensions to 2, by changing the dimension in lines 229-230 of dataset.py : `RuntimeError: Function AddmmBackward returned an invalid gradient at index 1 - got [1604, 65] but expected shape compatible with [1604, 66]`.
Experimenting with some other values for the dimension, I realized that the difference in dimension 1 of these error tensors is equal to `feature_dimension-1`. Can some model changes be suggested in order to allow higher feature dimensions?

**Comment by Lin-Yijie** [comment]
The problem may be caused by the gru module. I recommend for changing the gru module (lines 196 and 287) in [graphembeddingnetwork.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/graphembeddingnetwork.py) first.
Line 35 in graphembeddingnetwork.py ("def _build_model" in "class GraphEncoder") and [configure.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/configure.py) may also need to be changed but I'm not very sure. 
There may exist other solutions by changing the  "node_update_type='gru'" to "mlp" in [configure.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/configure.py).

**Comment by tathagatv** [comment]
@Lin-Yijie, changing `gru` to `mlp` didn't help. I found the following issues in the code which I believe are responsible for the problem:
1. Line 74 of [graphembeddingnetwork.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/graphembeddingnetwork.py) should be `edge_outputs = self.MLP2(edge_features)` instead of `edge_outputs = self.MLP2(node_features)`.
2. Line 178 and 188 of [graphembeddingnetwork.py](https://github.com/Lin-Yijie/Graph-Matching-Networks/blob/main/graphembeddingnetwork.py). The input dimension used is `self._edge_hidden_sizes[0] + 1`, it should instead be `self._edge_output_dim + 2*self._node_state_dim`. We need to additionally define `self._edge_output_dim` as the size of `edge_outputs` which is generated by `GraphEncoder`. The `2*self._node_state_dim` comes due to line 110 of graphembeddingnetwork.py, where we are appending the `node_features`.

The model is working fine after these changes.

**Comment by Lin-Yijie** [comment]
Thanks~ 
Could you please pull your recent code graphembeddingnetwork.py to this Repository? Thanks a lot for your help!
